---
- name: Delete Service
  k8s_v1_service:
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    state: absent

- name: Delete Route
  openshift_v1_route:
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    state: absent

- name: Delete ConfigMap
  k8s_v1_config_map:
    name: "{{ application_name }}"
    namespace: "{{ namespace}}"
    state: absent

- name: Delete PersistentVolumeClaim
  k8s_v1_persistent_volume_claim:
    name: "{{ application_name }}-claim"
    namespace: "{{ namespace}}"
    state: absent

- name: Delete DeploymentConfig
  openshift_v1_deployment_config:
    name: "{{ application_name }}"
    namespace: "{{ namespace}}"
    state: absent

- name: Delete ImageStream
  openshift_v1_image_stream:
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    state: absent
